# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none
variables:
  NUGET_HTTP_CACHE_PATH: $(cache)
pool:
  vmImage: ubuntu-latest
steps:
- script: echo Hello, $(NUGET_HTTP_CACHE_PATH)!

